### ISSUE TITLE
MIDI Learn UI issue in VST3 on Reaper

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#100] opened 2022-05-11 12:41 UTC
Hi, if you try to MIDI learn any PlugData param in Reaper the MIDI learn dialog window appears only PlugData VST3 window is closed. No other VST3 exhibit thsi issue.

**Comment by timothyschoen** [comment] 2022-05-11 15:33
That shouldn't happen, I'll see what's causing it.

**Comment by timothyschoen** [comment] 2022-05-12 01:27
I can't reproduce this unfortunately

**Comment by alfonso73** [comment] 2022-05-12 07:52
i'll make another video to be sure you made the very same steps...

**Comment by alfonso73** [comment] 2022-05-12 08:15
Here it is (done with latest build downloaded from action tab). 
GUI seems definitely more responsive!
But as you can see there's some strange thing about the MIDI Learn dialog window not appearing when PlugData window is open but only after i closed it.... pretty strange...mhhh....something to check in your Juce code about the main component? Just guessing...  https://streamable.com/ce16qx

**Comment by timothyschoen** [comment] 2022-05-12 11:39
I'm not doing anything unusual in my PluginEditor code that could cause this as far as I know... It's also unfortunate that this doesn't happen in REAPER on windows for me, makes it really hard to know what's going on.

**Comment by alfonso73** [comment] 2022-05-12 12:07
> I'm not doing anything unusual in my PluginEditor code that could cause this as far as I know... It's also unfortunate that this doesn't happen in REAPER on windows for me, makes it really hard to know what's going on.

Probably i should post a bug at Reaper's forum. What's strange is that the only one plugin that shows this behavior is actually PlugData so i suspect that could be somehow related to my particular Reaper configuration and PlugData...

**Comment by timothyschoen** [comment] 2022-05-12 13:00
Maybe a recent JUCE update is to blame? If it only happens for one plugin, I doubt it's reaper's fault

**Comment by alfonso73** [comment] 2022-05-16 11:43
I've found an interesting clue about this issue...i'll post a video in the following days. The problem seems to occur only when the PlugData parameters window is visible....

**Comment by alfonso73** [comment] 2022-05-23 15:13
In several moments in this video https://streamable.com/9akhkj you can see that the parameter window focus actually stole all control and the whole Reaper GUI won't work anymore until the PlugData parameter window is closed.

**Comment by timothyschoen** [comment] 2023-08-14 00:44
Does this still happen?

**Comment by timothyschoen** [comment] 2024-10-14 19:46
Closing because I don't think it still happens.

Let me know if it does though!

**Closed by timothyschoen** 2024-10-14 19:46 UTC
Labels: bug

**Comment by alfonso73** [comment] 2024-10-15 17:25
Everything seems to work fine. Thanks!
