### ISSUE TITLE
Saving an open patch that is currently cloned in another open patch causes a crash

### ISSUE THREAD

**Issue by MaxKablaam** [plugdata-team/plugdata#978] opened 2023-07-27 18:45 UTC
This is in v0.7.1, so if it's already been solved, my apologies.

Steps to reproduce:

1. Create a patch (patchA) with a few nodes in it
2. Save the patch
3. Create a new patch (patchB)
4. In patchB, create a clone node and clone patchA
5. Save patchB
6. Keep all patches open
7. Make some changes in patchA, then save it
8. Crash!

**Comment by tomara-x** [comment] 2023-07-28 15:54
can't reproduce on nightly, so hopefully that means it's fixed there :3

**Comment by timothyschoen** [comment] 2023-08-26 15:43
Should be fixed by cbcfabdeeae50a0fe31a8367a7892ad81c1f25fa!

**Closed by timothyschoen** 2023-08-26 15:43 UTC
