### ISSUE TITLE
Can't compile for daisy

### ISSUE THREAD

**Issue by Nek** [plugdata-team/plugdata#908] opened 2023-05-24 21:06 UTC
I have a basic patch that should compile. It's name is example.pd, so, it shouldn't create a problem, like mentioned in another bug. Still, I'm getting the same error.

```
--> Generating C

=== Signal Order ===
__phasor_k~f {frequency:0.0 phase:0.0}
__var_k~f {k:0.5 step:0 reverse:False}
__sub~f
__abs~f
__var_k~f {k:0.25 step:0 reverse:False}
__sub~f
__var_k~f {k:6.283185307179586 step:0 reverse:False}
__mul~f
__mul~f
__mul~f
__mul~f
__var_k~f {k:0.007833333333333 step:0 reverse:False}
__var_k~f {k:-0.166666666666667 step:0 reverse:False}
__fma~f
__fma~f
__line~f
__mul~f
__add~f
__add~f
AVX: 68.5 cycles / 8.5625 cycles per frame
     512 frames @ 1000MHz >= 4.38us
SSE: 63.5 cycles / 15.875 cycles per frame
     512 frames @ 1000MHz >= 8.13us
CPU% #Objs Object Type      Performance
==== ===== ================ ===========
18%  1     __phasor_k~f     Counter({'avx': 13, 'sse': 10})
 3%  5     __var_k~f        Counter({'avx': 2.5, 'sse': 2.5})
 8%  2     __sub~f          Counter({'avx': 6, 'sse': 6})
 0%  1     __abs~f          Counter({'avx': 0.5, 'sse': 0.5})
36%  5     __mul~f          Counter({'avx': 25, 'sse': 25})
14%  2     __fma~f          Counter({'avx': 10, 'sse': 10})
 8%  1     __line~f         Counter({'avx': 5.5, 'sse': 3.5})
 8%  2     __add~f          Counter({'avx': 6, 'sse': 6})
--> Generating Daisy module
  1) [91mError[0m c2daisy: Unknown parameter "freq"
Total compile time: 69.99ms
Compiling.../Users/nek/Library/plugdata/Toolchain/bin/arm-none-eabi-gcc -c -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard -DUSE_HAL_DRIVER -DSTM32H750xx -DHSE_VALUE=16000000  -DCORE_CM7 -DSTM32H750IB -DARM_MATH_CM7 -DUSE_FULL_LL_DRIVER -include stm32h7xx.h -I../../libdaisy -I../../libdaisy/src/ -I../../libdaisy/src/sys -I../../libdaisy/src/usbd -I../../libdaisy/src/usbh -I../../libdaisy/Drivers/CMSIS/Include/ -I../../libdaisy/Drivers/CMSIS/DSP/Include -I../../libdaisy/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../libdaisy/Drivers/STM32H7xx_HAL_Driver/Inc/ -I../../libdaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../libdaisy/Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../../libdaisy/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc -I../../libdaisy/core/ -I../../libdaisy/Middlewares/Third_Party/FatFs/src -O2 -Wall -Wno-missing-attributes -fasm -fdata-sections -ffunction-sections -Wno-stringop-overflow -g -ggdb -MMD -MP -MF"build/startup_stm32h750xx.d" -std=gnu11 -Wa,-a,-ad,-alms=build/startup_stm32h750xx.lst ../../libdaisy/core/startup_stm32h750xx.c -o build/startup_stm32h750xx.o
make: *** No rule to make target 'build/HeavyDaisy_example.o', needed by 'build/Heavy_example.elf'.  Stop.
make: *** Waiting for unfinished jobs....
```

Which as far as I can understand means Makefile is missing.
Another observation. When I generate a C++ Daisy project the source folder is missing the Makefile too.

**Comment by Nek** [comment] 2023-05-24 21:41
I've tried compiling the same patch from command line with hvcc installed with pip3 and it worked just fine.

**Comment by dromer** [comment] 2023-06-20 06:40
@Nek the error in your output says you are using a parameter called `freq` which is missing from your custom board definition, which is why the `c2daisy` step is failing.

Can you please share your patch and board.json files?

**Comment by timothyschoen** [comment] 2024-01-28 02:46
Closing because we need more information to solve this. We've also had several Heavy updates since this

**Closed by timothyschoen** 2024-01-28 02:46 UTC

**Comment by dromer** [comment] 2024-01-28 08:13
@timothyschoen the issue is likely not even with Heavy, but indeed without more info we can't help this user.

**Comment by Nek** [comment] 2024-01-28 08:35
Thanks for your effort! I'll check, if the latest version works. 🙏
