### ISSUE TITLE
Array: implement "vis f" message to edit multi-arrays

### ISSUE THREAD

**Issue by Omar-Misa** [plugdata-team/plugdata#1368] opened 2024-01-03 04:32 UTC
Having a GUI Array in a patch results in a crash at subsequent load.  This is the case even if the only content within a patch is one GUI Array.
The 'array' suite of objects run reliably.

Win10 64bit
PlugData 0.8.3 (standalone and VST3)

**Comment by timothyschoen** [comment] 2024-01-07 15:43
Fixed with 2adb535d3fd18f40b94ce0c1530a069dea3ca76d, thanks for reporting!

**Comment by timothyschoen** [comment] 2024-01-07 16:23
oops closed the wrong issue

**Comment by timothyschoen** [comment] 2024-01-10 17:17
I'm not able to reproduce this issue on Windows, does this happen every time when loading a patch with a GUI array?

**Comment by Omar-Misa** [comment] 2024-01-10 17:53
Thanks for your assessment, Tim.

Yes, it happened with about four patches i was working on that were of varying complexity.  The work was not lost as they loaded without issue in vanilla Pd.  i've now reverted to PlugData v0.8.2 to the relief of fully functioning patches, saved with GUI Arrays and with v0.8.3.  i didn't check for crashes on opening patch files saved in versions prior to 0.8.3.

If you're not able to reproduce the issue, then i trust that waiting for finalised release of v0.8.3 and its installation on my system  may alter my experience.

**Comment by timothyschoen** [comment] 2024-01-11 15:09
https://github.com/plugdata-team/plugdata/assets/44585538/be541921-7166-4643-9959-a7acf9e8dcab

No problems here, but if you send me one of the patches that causes the crash, I could test those, that might help. 

Or if that doesn't help, I can install Windows 10 in a VM, maybe that will make a difference?

**Comment by xeroooxed** [comment] 2024-01-11 19:35
[tape_looper_v3.zip](https://github.com/plugdata-team/plugdata/files/13907510/tape_looper_v3.zip)

Hi - same issue here! I'm uploading a simple patch with an array, but it is very simple to recreate on my end by just adding an array.

**Using plugdata 8.3 and win10 64bit.** 

A little bit of information: 
-I'm able to create from scratch the patch with an array and use it. I can save the patch. When trying to reopen, it will crash plugdata. The patch is no longer accessible. I can open and use it with Pure Data however. 
-It will immediately crash Ableton when loading the patch via plugdata vst.
-plugdata 8.2 crashes at startup on my computer. Maybe totally unrelated but whatever!

Many thanks for the support!

**Comment by timothyschoen** [comment] 2024-01-11 22:06
> [tape_looper_v3.zip](https://github.com/plugdata-team/plugdata/files/13907510/tape_looper_v3.zip)
> 
> Hi - same issue here! I'm uploading a simple patch with an array, but it is very simple to recreate the issue on my end by just adding an array to an empty patch.
> 
> **Using plugdata 8.3 and win10 64bit.**
> 
> A little bit of information:
> 
> -I'm able to create from scratch the patch with an array **and use it!** I can save the patch. When trying to reopen, it will crash plugdata. The patch is no longer accessible. I can open and use it with Pure Data, however. It looks like there is an issue when _loading_ the patch with an array.
> 
> -It will immediately crash Ableton when loading the patch via plugdata vst.
> 

Thanks, that helps!


> -plugdata 8.2 crashes at startup on my computer. Maybe totally unrelated but whatever!
> 

Yeah that's a known issue on Windows unfortunately. This is fixed in v0.8.3, I'm hoping to fix the array problem tomorrow as well :)

**Comment by timothyschoen** [comment] 2024-01-12 10:33
I tried this again on Windows 11, both opening your patch and the help patch, no crashes. So it's definitely starting to look like I need to install Windows 10 ;)

**Comment by Omar-Misa** [comment] 2024-01-13 03:42
Thanks for confirmation, xerooxed.  i've since found, however, that the issue seems to be particular to the build found here:
[https://github.com/plugdata-team/plugdata/releases/tag/v0.8.3-test](url)

Upon installation of a more recent nightly build (v0.8.3_12January2024), i'm finding that this issue no longer exists.  Nightly builds can be found here:
[https://plugdata.org/download.html](url)

…
On a related matter, pertaining to housing multiple arrays in one garray.  It's nice to interact with numerous arrays within a small footprint.  i'm finding that the "edit _integer_" method allows this.  To complete the experience, however, it would be good to have the "vis _integer_" method to have effect too.  i appreciate that this capacity is nery new addition to PlugData.

Thanks for both your attention.

**Comment by timothyschoen** [comment] 2024-01-15 15:11
> On a related matter, pertaining to housing multiple arrays in one garray. It's nice to interact with numerous arrays within a small footprint. i'm finding that the "edit _integer_" method allows this by giving user control over which array is editable. To complete the experience, however, it would be good to have the "vis _integer_" method to have effect too. i appreciate that this capacity is nery new addition to PlugData.

Good idea, I will add this soon!

**Comment by Omar-Misa** [comment] 2024-01-16 06:52
Thanks!

**Comment by timothyschoen** [comment] 2024-08-13 00:12
"vis f" work for me too now!

**Closed by timothyschoen** 2024-08-13 00:12 UTC
Labels: enhancement
