### ISSUE TITLE
Crash on loading Plaits help

### ISSUE THREAD

**Issue by rstecca** [plugdata-team/plugdata#1650] opened 2024-06-22 14:18 UTC
To reproduce:

1. Open plugdata and create a new patch
2. Add a Oscillators > Plaits node
3. Right click on the Plaits node
4. click Help

The application crashes 100% of the times for me.

I'm on Windows 11, plugdata 0.8.3

**Comment by porres** [comment] 2024-06-24 16:19
can you test with the nightly build?

**Comment by timothyschoen** [comment] 2024-06-25 14:22
I couldn't reproduce this on the latest nightly, so I'm hoping this is fixed now

**Closed** 2024-06-27 09:52 UTC
