### ISSUE TITLE
Bug: typing in object box cuts off/drops out early

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1846] opened 2024-09-07 11:07 UTC
I think it's since this commit: https://github.com/plugdata-team/plugdata/commit/42ee7fec130a637a07057c5007516a801d870bcc

As reverting to the one before that fixes it: https://github.com/plugdata-team/plugdata/commit/ddb180a0225441b07bb7a02f99e42127c8672469

**Comment by timothyschoen** [comment] 2024-09-10 14:08
What do you mean by "cuts off/drops out"?

**Comment by timothyschoen** [comment] 2024-09-10 14:20
Ah, I can reproduce!

**Comment by dromer** [comment] 2024-09-10 14:27
Ok good! (because I'm unable to build the latest commit >_<)

**Comment by timothyschoen** [comment] 2024-09-10 14:34
Fixed!

If the last commit fails to build, try the "-DENABLE_FFMPEG=0" flag. That will disable the new ffmpeg based audio players, I assume that's why you can't compile yet.

Or even better, there's the -DQUICK_BUILD=1 flag which disables ffmpeg, sfizz and Gem, so basically all objects that have large dependencies with complicated build systems.

I have pushed a fix, it now works for me on Fedora+Gnome. The original commit that caused this issue was actually intended to fix the problem you showed me at DMF, which is that the text editor was getting blocked from clicking by the shadow of the suggestion component. I also fixed the broken signal debugging on Linux, which we also discovered at DMF

**Closed** 2024-09-10 14:35 UTC

**Comment by dromer** [comment] 2024-09-10 14:38
Ok! I'll try the quick build
