### ISSUE TITLE
Little sluggishness in UI objects when automating with param

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#99] opened 2022-05-11 12:40 UTC
Hi, here's a patch with a simple slider controlled by a param in PlugData VST3.
If you use the param slider (or the relative automation coming from the host) you can see that the slider movement is kind of sluggish.
Can some Juce things be improved? Is there some interference between audio and UI threads? Given that some glitch are audible when PlugData UI is open and not when is closed i guess that some audio/GUI interference is present.
And this brings me to another question.
How to actually record automation using the actual UI (and not the param slider)?
Camomile has a mechanism to do this. (See its examples...the organ patch shows it very well)
Would be a great addition to PlugData.
[PlugData_0.52_param_test.pd.zip](https://github.com/timothyschoen/PlugData/files/8669953/PlugData_0.52_param_test.pd.zip)

**Comment by timothyschoen** [comment] 2022-05-11 15:28
Oh I'll definitely add an option to send automation as well!

How would you rate the sluggishness in the standalone? For me, it's much better. I use an entirely different mechanism there, it just reads/writes instantly from a list of thread-safe floats, I wonder if that works better for you as well. I'll look into why the performance is so much worse in the plugin.

**Comment by timothyschoen** [comment] 2022-05-11 16:40
Ah that makes it clear, I'll see what I can do.

**Comment by timothyschoen** [comment] 2022-05-11 23:56
I now remember that I'm updating automation once per DAW audio block. It would be better to do it every pure-data block, that way the distance is also more consistent if you change your daw settings.

**Comment by timothyschoen** [comment] 2022-05-12 00:53
I've implemented the faster update rate, code looks almost the same as Camomile now, except Camomile constantly sends the parameter messages, I only send them when the parameter changes.

**Comment by alfonso73** [comment] 2022-05-12 07:55
Great. No i'm not building by myself. I'll have to learn because i'll like to try to add some other externals to the VST3 version (i.e CEAMMC beacuse there are some stuff that ELSE does not have and maybe some externals by myself). How to download the latest version for the action tab?

**Comment by timothyschoen** [comment] 2022-05-12 11:24
@mathiasbredholt has a nice example of including extra libraries in this commit:

https://github.com/mathiasbredholt/PlugData/commit/0b8d7fed97cf3820e000b9eba7596b9972106b52

Instead of nicely putting it in the cmakelists like he did, you can also just jam it behind ELSE (in Libraries/cmakelists.txt):


<img width="714" alt="Screenshot 2022-05-12 at 13 21 55" src="https://user-images.githubusercontent.com/44585538/168063594-05f856ea-dac8-4752-b627-ec21b55fd595.png">


That might be simpler if you have no prior cmake experience.


Then the shittiest part is adding init functions for every object to Libraries/libpd/x_libpd_multi.c

It's not really a smooth workflow at the moment, and for ceammc I struggled to find the actual source code for just the library.

**Comment by mathiasbredholt** [comment] 2022-05-12 12:03
@timothyschoen yeah adding the init functions is quite the pain, would be nice to automate that process somehow :)

**Comment by alfonso73** [comment] 2022-05-12 15:52
>  and for ceammc I struggled to find the actual source code for just the library.

Yep it's quite a complex library. Basically what's really interesting is the aubio lib transient recognition/ audio analysis toolkit.
FFTease would be great too for FFT stuff. But we will see....

**Comment by timothyschoen** [comment] 2022-05-18 00:27
Sending automation will be added soon, it will work like this:

<img width="265" alt="Screenshot 2022-05-18 at 02 25 59" src="https://user-images.githubusercontent.com/44585538/168933146-7079eca4-4b76-4ac1-a877-49152827b4e2.png">

**Comment by alfonso73** [comment] 2022-05-18 09:50
@timothyschoen great! thanks

**Comment by alfonso73** [comment] 2022-05-19 17:48
@timothyschoen watch out for some feedback issues when having boh [r param1] and [s param1] working together.....

**Comment by alfonso73** [comment] 2022-05-19 18:02
mhhh...i'll send you a video of what's happening....but 'till monay probably i'll be very busy ....monday for sure!

**Comment by alfonso73** [comment] 2022-05-23 15:22
Hi @timothyschoen here's a video with an automation related test run with PlugData and Camomile.

https://streamable.com/9akhkj

It shows at least three areas of insterest that probably will deserve some design decision.

1. Parameter receiving and sending to and from host.
As you can see there's  some kind of feedback issue...look (video time code 09:05 and later ) at the periodic automation points generated while automating PlugData and the "spring-like" behavior of the parameter returning back at a fixed value.

2. A way to enter precise values (look at Camomile AlmondOrgan and the way number boxes are used)

3. Parameter mapping.
I think that parameters scaling (and probably even smoothing and log/exp curve coeeficients) should be a "parameter window" affaire (as in Camomile .txt file)

Thanks again for your great work and all the best for your presentation!

**Comment by timothyschoen** [comment] 2022-05-23 18:28
Thanks, I'll check out your video's soon!

**Comment by timothyschoen** [comment] 2022-05-28 01:31
The video made it much clearer! Turns out I made a mistake with sending the parameter change begin and end messages. I'm still unsure how to fix the focus issue, but I'll see if I can reproduce it on Windows tomorrow.

I agree that scaling and range should be handled in the parameter window eventually. I won't get to that this release, but definitely before the next one! I was going to do some rewriting for the automation panel anyways, because it's pretty slow right now.

If this bug is fixed you should be able to set precise values by hooking up a nbx or floatatom to the [s param] right? You can also do it by clicking the number in the automation panel, but it's not very nice yet. I'll make that better soon!

It seems to work fine now:

https://user-images.githubusercontent.com/44585538/170804532-8f1720ec-6067-4b75-a6e0-d39df063fdc1.mov

**Comment by alfonso73** [comment] 2022-05-28 19:09
still some strange "spring" behavior in automation "Touch mode" in Reaper.

https://streamable.com/fuew55

**Comment by alfonso73** [comment] 2022-07-02 21:04
Hi @timothyschoen! Still some strange things happens when automating parameters in "Touch" mode in Reaper....

**Comment by timothyschoen** [comment] 2022-07-02 21:57
Hi! I'm aware of it, I'm a bit confused because my code is very similar to Camomile, yet it behaves differently. It's also very annoying to have to restart the DAW every time I want to test a change, so I postponed this a little bit. I'll make sure it's fixed before next release though! I'll let you know when there's any progress!

**Comment by alfonso73** [comment] 2022-07-02 22:00
Thanks @timothyschoen !

**Comment by timothyschoen** [comment] 2022-08-20 19:46
I've come up with kind-of a solution. The problem is that reading and writing simultaneously is causing issues. So I just created a new subpatcher for PlugData, [param] that will allow both input and output, but makes sure there's only one happening at a time. This can be done (surprisingly reliably!) with a simple timed gate. All it does it make sure that there's no feedback between the send/receive.

This also makes it easier to figure out how to send/receive parameters!

The update will probably be up tomorrow, I'll let you know so you can test once more to see if it's finally solved now.

<img width="432" alt="Screenshot 2022-08-20 at 21 44 06" src="https://user-images.githubusercontent.com/44585538/185763735-87cd7e17-18af-4bbe-b73a-b1eb2c5cf493.png">

<img width="432" alt="Screenshot 2022-08-20 at 21 42 53" src="https://user-images.githubusercontent.com/44585538/185763715-fd13b719-3b27-4e81-9a44-6d9a913b1629.png">

**Comment by alfonso73** [comment] 2022-08-22 09:40
Great! If a lot of parameters are involved could it be a little heavy on CPU? i remember of Pierre's solution for Camomile... https://github.com/pierreguillot/Camomile/issues/121#issuecomment-404784189

**Comment by timothyschoen** [comment] 2022-08-23 15:32
It's still not great :(

Everything I was planning to do before v0.6 is done, so I guess this one is gonna get postponed even more... The good news is that as long as you don't read and write simultaneously (things like touch mode) it should be okay.

**Comment by timothyschoen** [comment] 2022-08-31 17:32
Looks like it's working now! I've added a manual "change" mode, similar to what Camomile has. That helps a lot. I've found that automation feels more responsive in general now, and it also behaves normally in touch/write mode. New version will be up later today!

**Comment by timothyschoen** [comment] 2022-09-07 23:26
>     2. A way to enter precise values (look at Camomile AlmondOrgan and the way number boxes are used)
> 
>     3. Parameter mapping.
>        I think that parameters scaling (and probably even smoothing and log/exp curve coeeficients) should be a "parameter window" affaire (as in Camomile .txt file)

Entering precise values should be possible, by clicking on the number in the automation panel.

I was a long way into implementing range for the automation panel, but I then realised that it is impossible to do this. The DAW needs to know the range of the parameter at startup, there's no way around that :(

So I guess that since I already have a [param] object, I'll just allow sending messages into that for setting the range.

**Comment by alfonso73** [comment] 2022-09-08 14:04
> > ```
> > 2. A way to enter precise values (look at Camomile AlmondOrgan and the way number boxes are used)
> > 
> > 3. Parameter mapping.
> >    I think that parameters scaling (and probably even smoothing and log/exp curve coeeficients) should be a "parameter window" affaire (as in Camomile .txt file)
> > ```
> 
> Entering precise values should be possible, by clicking on the number in the automation panel.
> 
I guess that an abstraction example with a num box and a slider being associated to the same automation parameter would be great. It's quite difficult to set a precise value in the 0.0 - 1.0 range of the parameter as seen by the DAW host. It's better to specify values in the actual patch with numbers and values that are meaningful for the actual patch.

**Comment by timothyschoen** [comment] 2023-01-23 17:00
<img width="885" alt="Screenshot 2023-01-23 at 17 57 17" src="https://user-images.githubusercontent.com/44585538/214101259-9fc284e3-faa8-4dd3-9ba3-f689b6b8ce88.png">

I've added a whole new parameter system that allows you to create named parameters, with a custom range.

If you could try a recent build to see if parameters are less sluggish now, that would be nice! You'll have to delete plugdata's internal folder when you update to make sure the new [param] abstraction gets unpacked.

Because if this update doesn't work, I can also start using Camomile's method of outputting parameter values in a constant stream. This would be more okay now that we can set up a custom number of parameters.

**Comment by alfonso73** [comment] 2023-01-24 00:57
Great! I'll give it a quick run tomorrow!

**Comment by alfonso73** [comment] 2023-01-24 14:33
Made a little test.
It's seems better but still some problems.

1. "Touch" automation mode in Reaper does not work properly as the other plugins do
2. When writing automation (only "Write" and "Latch" modes seem to work properly) there are various audio glirches...is the GUI thread interfering with audio thread?
3. When in "Read/Trim" mode is impossible to operate on PlugData GUI faders being automated.

**Comment by alfonso73** [comment] 2023-01-24 16:17
An interesting thing about Camomile was the way it works with automation with sliders and numboxes so it's possible to visualize sliders' values and input specific values in the numboxes. Both sliders and numboxes are automatable.
Here
https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#parameters
and here
https://github.com/pierreguillot/Camomile/issues/121#issuecomment-404784189

**Comment by alfonso73** [comment] 2023-01-24 16:55
Probably a good idea could be to add to the param astractions four new fields to set receive and send symbols for GUI widgets (sliders, knobs, etc) and numboxes to avoid huge spaghettis in patches and to add additional send and receives as here...
![image](https://user-images.githubusercontent.com/3230434/214357162-7ec39f1e-0366-479d-8132-36fad2e700e4.png)

**Comment by alfonso73** [comment] 2023-01-24 21:14
I just made a little abstraction that makes life little easier

![image](https://user-images.githubusercontent.com/3230434/214417055-a3278931-f3e8-45bb-920f-285418654558.png)

![image](https://user-images.githubusercontent.com/3230434/214417240-ab56de65-33a2-4a37-8edc-e185048cad57.png)

I noticed that when sliders are set to logarithmic when i open the Daw project the sliders are set at wrong values.
Probably in the PlugData parameters dialog a coresponding logarithmic option should be available?

**Comment by timothyschoen** [comment] 2023-01-25 12:41
Thanks for figuring this out, I'll go over this tomorrow!

**Comment by alfonso73** [comment] 2023-01-25 12:51
Thanks for yours and plugdata team's great work!

**Comment by timothyschoen** [comment] 2023-01-29 01:12
> 1. "Touch" automation mode in Reaper does not work properly as the other plugins do

I tried it, it does seem to work for me, but you need to send a "1" into the second inlet of [param] to indicate that you want to write automation. You can also attach the first outlet of [canvas.mouse] to that, to automatically go into write mode when dragging the mouse.

>  2. When writing automation (only "Write" and "Latch" modes seem to work properly) there are various audio glirches...is the GUI thread interfering with audio thread?

Can't reproduce this, I'll try again later on Windows.

> 3. When in "Read/Trim" mode is impossible to operate on PlugData GUI faders being automated.

I can reproduce this, I'll see what I can do about that!

**Comment by timothyschoen** [comment] 2023-01-30 10:07
I think I know where the audio glitches are coming from, I stopped the plugin's audio every time the DAW would ask the plugin to save, for thread-safety reasons. But I realise now that the DAW might ask to save pretty often and randomly, and in this case, it might want to save because you've changed a parameter.

I'm now just locking the audio thread instead of stopping it entirely. Not perfect, but probably better.

**Comment by alfonso73** [comment] 2023-01-30 12:33
Yeah that could be a reason. I see that when i move some slider there's small PlugData feezes freezes for a while. BTW i wonder if Juce should take account of the GUI and Audio threads separation...

**Comment by timothyschoen** [comment] 2023-01-30 12:36
> BTW i wonder if Juce should take account of the GUI and Audio threads separation...

Pure-data is too complicated to let JUCE take care of that, it can only really help you when you have a simple plugin with only a bunch of knobs.

Pd runs on the audio thread, so that it can output sound, but all the GUI interaction happens on the GUI thread. I mostly solve this with a lock-free message queue, but sometimes (especially when saving/loading files or doing other big actions) locking is required.

**Comment by alfonso73** [comment] 2023-01-30 13:00
Oh i understand. Is the new lock-free message already available in the latest version?

**Comment by timothyschoen** [comment] 2023-01-30 13:25
Yes it is, so let me know if you still experience the same problem!

**Comment by alfonso73** [comment] 2023-01-30 13:55
> Yes it is, so let me know if you still experience the same problem!

Sadly is still not working properly. As soon i move a GUI widaget linked to a param as soon as i release the mouse botton the whole Reaper audio freezes for a little while then starts again.

**Comment by alfonso73** [comment] 2023-01-30 14:29
> I tried it, it does seem to work for me, but you need to send a "1" into the second inlet of [param] to indicate that you want to write automation. You can also attach the first outlet of [canvas.mouse] to that, to automatically go into write mode when dragging the mouse.
> 
I have connected a [canvas.mouse] to second inlet of [param] and i have the console reporting "parameter change (param name here) not started. I'll share a video showing this and the audio freeze thing after i moved a GUI widget linked to a [param]

**Comment by alfonso73** [comment] 2023-01-31 10:38
The feezing after GUI widget connected to [param] happens in VST3 only and not in CLAP and LV (i'm testing with latest Reaper on Win11)

**Comment by alfonso73** [comment] 2023-02-01 21:37
> The feezing after GUI widget connected to [param] happens in VST3 only and not in CLAP and LV (i'm testing with latest Reaper on Win11)

It seems to be solved with latest version...

**Comment by alfonso73** [comment] 2023-02-03 13:02
Issue is still here :-( The issue about parameters and freeze exists in all three plugin version VST3/CLAP/LV2. It seemd to me that existed in VST3 only because i forgot to add parameters in CLAP and LV2 (parameters are linked to plugin instance and not to patch obviously). Here's a video. As you can see the freeze occurs in both cases of moving from patch GUI and from Parameters dialog. https://streamable.com/4l2vyw

**Comment by timothyschoen** [comment] 2023-02-06 02:52
I think 0bcdf4e solved it for real this time!

First of all, I've taken an even closer look at how Camomile handles its parameters, and I did find some differences. I've made plugdata's parameters behave more like Camomile, except that it still filters out repeated values like it used to. I've tested it a bit, and everything is so much smoother, it's a huge difference!

I'm now also using the same way of handling the DAWs parameter change messages as camomile, if you pass the argument "1" to the param object after the name (so it would be [param gain 1]), it will automatically send parameter change messages whenever you click on any slider/numbox/radiobox. It should work for most pd-vanilla gui objects at least. I've made this opt-in because it's not always desirable to have this done automatically for you.

I've also added send/receives into the [param] abstraction like you said.
<img width="664" alt="Screenshot 2023-02-06 at 03 43 03" src="https://user-images.githubusercontent.com/44585538/216871495-53f4d761-b7dc-4180-8b0a-e6829bc76c7c.png">

If you want to try the new [param] object (now with helpfile as well!), don't forget to clear out plugdata's folder.

One thing: I've primarily tested this in Logic, I still have to test in REAPER and some other DAWs.

**Comment by timothyschoen** [comment] 2023-02-06 03:36
I tested it in REAPER now as well, it seems to work perfectly!

**Comment by timothyschoen** [comment] 2023-02-06 12:12
You can paste this into plugdata, make sure the params "param1" and "param2" exist:
```
#X obj 145 178 param param1, f 13;
#X obj 278 178 hsl 128 17 0 127 0 0 empty empty empty -2 -8 0 10 #e4e4e4 #5a5a5a #5a5a5a 0 1;
#X obj 216 139 tgl 25 0 empty empty empty 17 7 0 10 #e4e4e4 #5a5a5a #5a5a5a 0 1;
#X obj 474 171 param param2 1;
#X obj 592 170 nbx 5 18 -1e+37 1e+37 0 0 param2-gui-s param2-gui-r empty 0 -8 0 10 #e4e4e4 #5a5a5a #5a5a5a 0 256;
#X connect 0 0 1 0 empty;
#X connect 1 0 0 0 empty;
#X connect 2 0 0 1 empty;
```

The left side shows you how to send manual DAW change messages, the right one will do it automatically and sync with a numbox.

https://user-images.githubusercontent.com/44585538/216968033-98efb9c1-fac7-4955-9658-bec79b071e4e.mov

**Comment by alfonso73** [comment] 2023-02-06 12:40
Thanks! so if i need a slider and a numbox fpr the same parameter i'd just use same send/receive symbols for both the slider and the numbox right? Probably if i interact with the slider both slider and numbox will send their values to DAW right? ANd viceversa if i iteract with the numbox they would send their activity to the DAW. I wonder if it's an efficient way of dealing with a slider and numbox pair for the same parameter being the numbox used for monitoring the actual value and to enter precise values.

**Comment by timothyschoen** [comment] 2023-02-06 12:42
That's something I haven't tried yet, but I guess that if it works in Camomile, it should also work in plugdata?

Worst case scenario you'd need to remove the send from the numbox, so it can only receive values, that way you're sure there can never be any feedback loops.

**Comment by alfonso73** [comment] 2023-02-06 12:45
Yeah but that way i wouldn't be able to use the numbox to insert values. If you take a look at the Almond Organ example in Camomile there you should have an idea on how Camomile deals with this scenario.

**Comment by alfonso73** [comment] 2023-02-06 12:48
BTW everything is a lot smoother now! We're on the right way!

**Comment by timothyschoen** [comment] 2023-02-06 12:52
<img width="294" alt="Screenshot 2023-02-06 at 13 49 16" src="https://user-images.githubusercontent.com/44585538/216975670-453fdd35-4a0a-49b0-b533-6f69e77c7593.png">

I see, it basically uses a combination of chaining messages and using the "set" message to set it without outputting.

I can probably include this in the [param] abstraction, but instead of explicitly saying "this one is for slider", "this one is for numbox", it might be better to just use generic names, like $0-gui1-s $0-gui2-s, so that it doesn't give the impression that it's exclusively for sliders and numboxes?

**Comment by timothyschoen** [comment] 2023-02-06 13:07
hmm this works, but you actually do need to have 2 objects to make it work. So maybe doing this in a separate abstraction would be better?

**Comment by timothyschoen** [comment] 2023-02-06 13:17
Maybe allow specifying the name of the send as well?

So you can do: [param.two paramName sld nbx]

And then you get the sends as paramName-sld-s/paramName-nbx-r etc.

**Comment by timothyschoen** [comment] 2023-02-06 13:18
> BTW everything is a lot smoother now! We're on the right way!

I'm very happy with this, finally some good fucking automation!

**Comment by alfonso73** [comment] 2023-02-06 13:36
Hell yeah man! That's a great avancement! Thanks!

**Comment by alfonso73** [comment] 2023-02-06 14:31
oh BTW [set ( is not working for Number Box

**Comment by alfonso73** [comment] 2023-02-06 16:22
something like this...
![image](https://user-images.githubusercontent.com/3230434/217026607-a87a2fdd-24c8-42dd-a2ca-c90472bf61c7.png)

**Comment by alfonso73** [comment] 2023-02-06 16:43
uh and then i realized that there's no common data space between different PlugData VST3/CLAP/LV2 instances. So i guess $0 doesn't have any meaning.... am i right? I guess the only thing is about porting to PlugData standalone or plain vanilla...so probably i'll include in the param.pair abstraction a place holder for $0 so if the patch is used in multiple copies in a vanilla or standalone context everything would work fine.

**Comment by timothyschoen** [comment] 2023-02-06 16:49
There isn't any shared dataspace between different plugin instances, but there is between different opened patches, so better to be safe and put $0 before it.

> oh BTW [set ( is not working for Number Box. Well it functionally because the value is actually set but the number box UI is not updated

Thanks for letting me know, should be fixed!

**Comment by timothyschoen** [comment] 2023-02-07 16:43
I think the original issue here is solved, so your new report will be the continuation of the discussion on DAW parameter improvements.

**Closed by timothyschoen** 2023-02-07 16:43 UTC
Labels: bug

**Comment by alfonso73** [comment] 2023-02-07 16:50
Yeah i guess. I still hear some glitches when automating but it's far better and usable. For audio "perfection" i guess i have to do more specific tests and eventually reopen here or submit another issue. Do you agree?

**Comment by timothyschoen** [comment] 2023-02-07 16:56
> Yeah i guess. I still hear some glitches when automating but it's far better and usable. For audio "perfection" i guess i have to do more specific tests and eventually reopen here or submit another issue. Do you agree?

You can open a new one for that, because it's unrelated to the problems we were having here. Maybe you have sent me this already and I forgot, but if you have a patch I can try that exhibits audio glitches when dragging parameters, that would help. I haven't been able to reproduce that problem yet.

**Comment by alfonso73** [comment] 2023-02-07 18:13
cool. i'll do more testing in that specific area
