### ISSUE TITLE
Shortcut for object connection issue

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1203] opened 2023-09-30 12:31 UTC
Under MacOS, CMD + k make a connection only if object are selected  in reverse order (second box, then first box).
Tested with last Actions build.

**Comment by timothyschoen** [comment] 2023-09-30 15:26
This is a duplicate of https://github.com/plugdata-team/plugdata/issues/945

But yeah, I really need to fix it!

**Closed by timothyschoen** 2023-09-30 15:26 UTC
