### ISSUE TITLE
Undo/Redo weirdness

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#1866] opened 2024-09-25 20:51 UTC
I'm encountering some strange behaviour when undo-ing / redo-ing during patching.

For example:

1. Sometimes not all objects are moved back when multiple are selected, I move them, but then decide to undo the move. Some objects stick around. Below is illustrated what happens to me when using undo after a drag of multiple objects. At some point plugData really has no idea anymore where objects came from. Also if I decide to move a single object all of a sudden but undo that.

![ScreenRecording2024-09-25at22 39 54-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/de533ab7-a4a2-4ad8-a9ee-7b37dbf09d92)

2. When creating an object, then hitting enter, then starting a new-object, but instead of continuing I decide now, i hit undo, but then the previous object is deleted, instead of removing the empty object, which I would expect.

![ScreenRecording2024-09-25at22 47 34-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/e9ffa063-0ee6-40c4-92ab-538c3c4adf68)

**Comment by timothyschoen** [comment] 2024-09-25 21:33
Oh, I was aware there were still some undo issues, thanks for giving some examples. I'll fix these!

**Comment by tmhglnd** [comment] 2024-09-25 22:15
Thanks for giving it a look!

**Comment by timothyschoen** [comment] 2024-09-30 16:46
68b195703 should fix issues 1 and 2!

**Comment by tmhglnd** [comment] 2024-10-02 13:28
I can replicate this issue. But, when I move the objects 2x or more I can undo once. Although clearly some undo history gets messed up in the process. Because if I follow these steps this is what happens:

1. Add 2 objects
2. Select them and move them with arrow keys 2x times
3. Undo 1x (they move back one step)
4. Undo 1x (last object added is deleted..., this should be moving back one more time)

**Comment by timothyschoen** [comment] 2024-10-03 11:26
> OK to add another issue here?
> 
>     1. Mouse select an object or two.
> 
>     2. Arrow-key move them on the canvas.
> 
>     3. Undo -- nothing happens.

I can only reproduce this on v0.9.1, but not anymore on the nightly builds for v0.9.2. So maybe this is already fixed?

**Comment by timothyschoen** [comment] 2024-10-03 14:07
> Thanks for giving it a look! Just wanted to add one more little thing:
> 
>     3. In bigger patches, after moving one thing and undo-ing, everything just moves a little bit, like only a few pixels.
> 
> 
> ![ScreenRecording2024-09-26at00 16 04-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/8721936/370911610-b0a5635d-8c6d-4c32-9bc0-7384dcedba90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjQ0NTUsIm5iZiI6MTcyNzk2NDE1NSwicGF0aCI6Ii84NzIxOTM2LzM3MDkxMTYxMC1iMGE1NjM1ZC04YzZkLTRjMzItOWJjMC03Mzg0ZGNlZGJhOTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTQwMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmZjk4ZTY1YTkwZWNkZDJjNDVjMWFiYTJjNDkzYjg4NmRjNTg4YjVlY2QwMmUzMTQ0ZTQ5NDY1MmUzZjQxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-maZQmtXdmpbkFdiP2dfUQ4k3tk4a1SWmsCu7WZ1854) [ ![ScreenRecording2024-09-26at00 16 04-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/8721936/370911610-b0a5635d-8c6d-4c32-9bc0-7384dcedba90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjQ0NTUsIm5iZiI6MTcyNzk2NDE1NSwicGF0aCI6Ii84NzIxOTM2LzM3MDkxMTYxMC1iMGE1NjM1ZC04YzZkLTRjMzItOWJjMC03Mzg0ZGNlZGJhOTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTQwMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmZjk4ZTY1YTkwZWNkZDJjNDVjMWFiYTJjNDkzYjg4NmRjNTg4YjVlY2QwMmUzMTQ0ZTQ5NDY1MmUzZjQxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-maZQmtXdmpbkFdiP2dfUQ4k3tk4a1SWmsCu7WZ1854) ](https://private-user-images.githubusercontent.com/8721936/370911610-b0a5635d-8c6d-4c32-9bc0-7384dcedba90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjQ0NTUsIm5iZiI6MTcyNzk2NDE1NSwicGF0aCI6Ii84NzIxOTM2LzM3MDkxMTYxMC1iMGE1NjM1ZC04YzZkLTRjMzItOWJjMC03Mzg0ZGNlZGJhOTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTQwMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmZjk4ZTY1YTkwZWNkZDJjNDVjMWFiYTJjNDkzYjg4NmRjNTg4YjVlY2QwMmUzMTQ0ZTQ5NDY1MmUzZjQxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-maZQmtXdmpbkFdiP2dfUQ4k3tk4a1SWmsCu7WZ1854) [ ](https://private-user-images.githubusercontent.com/8721936/370911610-b0a5635d-8c6d-4c32-9bc0-7384dcedba90.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjQ0NTUsIm5iZiI6MTcyNzk2NDE1NSwicGF0aCI6Ii84NzIxOTM2LzM3MDkxMTYxMC1iMGE1NjM1ZC04YzZkLTRjMzItOWJjMC03Mzg0ZGNlZGJhOTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTQwMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmZjk4ZTY1YTkwZWNkZDJjNDVjMWFiYTJjNDkzYjg4NmRjNTg4YjVlY2QwMmUzMTQ0ZTQ5NDY1MmUzZjQxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-maZQmtXdmpbkFdiP2dfUQ4k3tk4a1SWmsCu7WZ1854)

This also appears to be fixed on nightly builds. On v0.9.1, it still happened for me with metro-help.pd, but in v0.9.2 (nightly) it no longer does.

**Comment by tmhglnd** [comment] 2024-10-03 19:04
You're right, number `3` is fixed for me in `0.9.2`! Great!

Number `2` is fixed as well! Although for me it requires 2x undo to get rid of the box. But nevertheless better than how it worked before, thanks.

Number `1` is as good as fixed, although I still see a small movement in the object when `cmd-z` is used. But it is tiny... It is no big deal but just for completion wanted to mention it, haha.

![Untitled-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/b16a32dd-f9ae-4f05-8a21-3bb63934c7db)

**Comment by timothyschoen** [comment] 2024-10-03 23:08
> You're right, number `3` is fixed for me in `0.9.2`! Great!
> 
> Number `2` is fixed as well! Although for me it requires 2x undo to get rid of the box. But nevertheless better than how it worked before, thanks.
> 
> Number `1` is as good as fixed, although I still see a small movement in the object when `cmd-z` is used. But it is tiny... It is no big deal but just for completion wanted to mention it, haha.
> 
> ![Untitled-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/8721936/373381227-b16a32dd-f9ae-4f05-8a21-3bb63934c7db.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTYwMjksIm5iZiI6MTcyNzk5NTcyOSwicGF0aCI6Ii84NzIxOTM2LzM3MzM4MTIyNy1iMTZhMzJkZC1mOWFlLTRmMDUtOGEyMS0zYmI2MzkzNGM3ZGIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMjI0ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI4MzliNTQ5NzFjMmZiOWU3OTdjOGUwZjFlMTQ5OTEyZmRlYzA1NTliM2E0MDJhNThhYTc0YjdkNDBjNDdhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0-3kA4T1U59uF750tA1jOQk6PLUPA5N_RLN3HEfmAEE) [ ![Untitled-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/8721936/373381227-b16a32dd-f9ae-4f05-8a21-3bb63934c7db.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTYwMjksIm5iZiI6MTcyNzk5NTcyOSwicGF0aCI6Ii84NzIxOTM2LzM3MzM4MTIyNy1iMTZhMzJkZC1mOWFlLTRmMDUtOGEyMS0zYmI2MzkzNGM3ZGIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMjI0ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI4MzliNTQ5NzFjMmZiOWU3OTdjOGUwZjFlMTQ5OTEyZmRlYzA1NTliM2E0MDJhNThhYTc0YjdkNDBjNDdhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0-3kA4T1U59uF750tA1jOQk6PLUPA5N_RLN3HEfmAEE) ](https://private-user-images.githubusercontent.com/8721936/373381227-b16a32dd-f9ae-4f05-8a21-3bb63934c7db.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTYwMjksIm5iZiI6MTcyNzk5NTcyOSwicGF0aCI6Ii84NzIxOTM2LzM3MzM4MTIyNy1iMTZhMzJkZC1mOWFlLTRmMDUtOGEyMS0zYmI2MzkzNGM3ZGIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMjI0ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI4MzliNTQ5NzFjMmZiOWU3OTdjOGUwZjFlMTQ5OTEyZmRlYzA1NTliM2E0MDJhNThhYTc0YjdkNDBjNDdhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0-3kA4T1U59uF750tA1jOQk6PLUPA5N_RLN3HEfmAEE) [ ](https://private-user-images.githubusercontent.com/8721936/373381227-b16a32dd-f9ae-4f05-8a21-3bb63934c7db.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTYwMjksIm5iZiI6MTcyNzk5NTcyOSwicGF0aCI6Ii84NzIxOTM2LzM3MzM4MTIyNy1iMTZhMzJkZC1mOWFlLTRmMDUtOGEyMS0zYmI2MzkzNGM3ZGIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMjI0ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI4MzliNTQ5NzFjMmZiOWU3OTdjOGUwZjFlMTQ5OTEyZmRlYzA1NTliM2E0MDJhNThhYTc0YjdkNDBjNDdhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0-3kA4T1U59uF750tA1jOQk6PLUPA5N_RLN3HEfmAEE)

Seems to be an issue specific to sliders, I don't get it with toggles. Pretty strange, I'll take a look at it later

**Comment by tmhglnd** [comment] 2024-10-04 20:55
Not sure if this is related to the undo/redo history, but maybe it is:

4. When `option-dragging` an object (or group) to copy it, then do something else (like connecting something to this object, or copying some other objects, or creating an object), the object(s) jump back to it's "origin" (near the original object of where it was copied from). It seems the location after the copy-drag is not saved.

![ScreenRecording2024-10-04at22 52 59-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/dce099ad-31ce-4abd-a13f-14dd72ef789c)

**Comment by timothyschoen** [comment] 2024-10-04 23:42
> Not sure if this is related to the undo/redo history, but maybe it is:
> 
>     4. When `option-dragging` an object (or group) to copy it, then do something else (like connecting something to this object, or copying some other objects, or creating an object), the object(s) jump back to it's "origin" (near the original object of where it was copied from). It seems the location after the copy-drag is not saved. Using the `0.9.2` nightly build.
> 
> 
> ![ScreenRecording2024-10-04at22 52 59-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/8721936/373805894-dce099ad-31ce-4abd-a13f-14dd72ef789c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODU0NTcsIm5iZiI6MTcyODA4NTE1NywicGF0aCI6Ii84NzIxOTM2LzM3MzgwNTg5NC1kY2UwOTlhZC0zMWNlLTRhYmQtYTEzZi0xNGRkNzJlZjc4OWMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMjMzOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM5ZjE3MzU5NmE1N2VhMTk1YWVkMWJhOTlkOWVmZTVhYzllZDY1MmE1YzBkZjYzYjcxNTg1MGIwNmQ5MmQ2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YPuitJqMOnjWaRHxuAuhNKjBP0kmoL2AcFheTT6qbeU) [ ![ScreenRecording2024-10-04at22 52 59-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/8721936/373805894-dce099ad-31ce-4abd-a13f-14dd72ef789c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODU0NTcsIm5iZiI6MTcyODA4NTE1NywicGF0aCI6Ii84NzIxOTM2LzM3MzgwNTg5NC1kY2UwOTlhZC0zMWNlLTRhYmQtYTEzZi0xNGRkNzJlZjc4OWMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMjMzOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM5ZjE3MzU5NmE1N2VhMTk1YWVkMWJhOTlkOWVmZTVhYzllZDY1MmE1YzBkZjYzYjcxNTg1MGIwNmQ5MmQ2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YPuitJqMOnjWaRHxuAuhNKjBP0kmoL2AcFheTT6qbeU) ](https://private-user-images.githubusercontent.com/8721936/373805894-dce099ad-31ce-4abd-a13f-14dd72ef789c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODU0NTcsIm5iZiI6MTcyODA4NTE1NywicGF0aCI6Ii84NzIxOTM2LzM3MzgwNTg5NC1kY2UwOTlhZC0zMWNlLTRhYmQtYTEzZi0xNGRkNzJlZjc4OWMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMjMzOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM5ZjE3MzU5NmE1N2VhMTk1YWVkMWJhOTlkOWVmZTVhYzllZDY1MmE1YzBkZjYzYjcxNTg1MGIwNmQ5MmQ2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YPuitJqMOnjWaRHxuAuhNKjBP0kmoL2AcFheTT6qbeU) [ ](https://private-user-images.githubusercontent.com/8721936/373805894-dce099ad-31ce-4abd-a13f-14dd72ef789c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODU0NTcsIm5iZiI6MTcyODA4NTE1NywicGF0aCI6Ii84NzIxOTM2LzM3MzgwNTg5NC1kY2UwOTlhZC0zMWNlLTRhYmQtYTEzZi0xNGRkNzJlZjc4OWMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMjMzOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM5ZjE3MzU5NmE1N2VhMTk1YWVkMWJhOTlkOWVmZTVhYzllZDY1MmE1YzBkZjYzYjcxNTg1MGIwNmQ5MmQ2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YPuitJqMOnjWaRHxuAuhNKjBP0kmoL2AcFheTT6qbeU)

Oh, yep I messed this up when fixing the undo bug! Should be fixed with aa7a82add

**Comment by timothyschoen** [comment] 2024-10-06 10:28
> Number `2` is fixed as well! Although for me it requires 2x undo to get rid of the box. But nevertheless better than how it worked before, thanks.

Fixed that with 47b9c5043

I think that covers all of them, except for the issue that only applies to hslider (which is probably related to the object instead of undo/redo itself).

But feel free to comment on this issue if you find more undo/redo problems, I'll reopen it.

**Closed by timothyschoen** 2024-10-06 10:28 UTC
Labels: bug, gui

**Comment by tmhglnd** [comment] 2024-10-06 10:38
Awesome thanks! Will check it out soon. The nightly build installer currently gives the error: "The installer is damaged", tho.
