### ISSUE TITLE
DAW crashes when I try to open my VST patch for the *second* time

### ISSUE THREAD

**Issue by glocq** [plugdata-team/plugdata#266] opened 2022-12-13 12:58 UTC
Hi, I'm trying out PlugData as a VST from within Reaper on Linux. I'm working on some patch. If I open the patch for the first time since launching Reaper, things are fine. However, if I close it and open it again, Reaper crashes with a segmentation fault.

Additional info: sometimes before the crash, I can hear a saw wave of about 170Hz for a couple of tenths of a second. Since there's no audio output in my PD patch (and no VSTs apart from PlugData), I'm suspecting it might be due to some code I might have intended to delete but got saved somehow even though it's not visible anymore?

[Here](https://github.com/plugdata-team/plugdata/files/10217995/plugdata.RPP.txt) is the Reaper project file, disguised as a text file (it is text after all) because Github won't accept .RPP files. And [here](https://github.com/plugdata-team/plugdata/files/10217982/segfault.pd.txt) is the PD patch on its own, disguised as a text file too (it is also textual data).
 
Steps to reproduce:
1. Remove the .txt extension from the Reaper file provided above;
2. Open file with Reaper;
3. Click *fx* in the only track to show the GUI of that track's plugin, namely PlugData with my patch;
4. Close the *fx* window;
5. (try to) Open it again.

Reaper should then crash.

**Comment by timothyschoen** [comment] 2022-12-17 14:32
Unfortunately I'm not able to reproduce this crash with Reaper on Linux, although I tried it on an ARM machine, I'll try x64 later as well.

Did you get plugdata through the released binaries or through the OBS repository?

**Comment by glocq** [comment] 2022-12-17 14:38
Thank you for taking the time to look into it. It truly is a weird bug...
I got it through the OBS repository.

**Comment by tomara-x** [comment] 2022-12-17 15:30
i tried opening your patch file and then closing the window, it will crash. but if i delete the subpatch "pd restart" then i can close and reopen the window without any problems. i'm doing this on bitwig (plugdata v0.6.3 from the actions build on void linux)

**Comment by glocq** [comment] 2022-12-17 17:47
Just tried deleting the subpatch too, still crashes on my machine.

**Comment by glocq** [comment] 2022-12-20 09:32
Update: just updated plugdata, now it crashes when I close the interface for the first time — not when I try to open it for the second time.

I've been able to make a minimal example of a patch that makes reaper crash: [pd patch](https://github.com/plugdata-team/plugdata/files/10267105/patch.pd.txt) and [reaper project](https://github.com/plugdata-team/plugdata/files/10267104/plugdata.RPP.txt), again both disguised as text files,

although the patch is simple enough that it can be reproduced here in text form:
```
[phasor~ 1]
 |
[pd restart]
```
with the subpatch `restart` containing:
```
[inlet~]
 |
[!-~ 0]
 |
[threshold~ -0.1 0 -0.9 0]
```

**Comment by timothyschoen** [comment] 2022-12-20 10:40
Hi, thanks for figuring that out! I'm sick right now so I'll test it later

**Comment by glocq** [comment] 2022-12-20 10:57
No worries! Get well soon

**Comment by timothyschoen** [comment] 2023-01-06 23:57
I've recently fixed many bugs that were specific to the DAW version, so I'm very curious if this bug still happens. I was unfortunately never able to reproduce it myself.

**Comment by tomara-x** [comment] 2023-01-07 00:18
beautiful! this was making me scared to close the pd window! just tested now in bitwig and reaper, and at least what i was experiencing is now fixed. both my clone abstraction patches and op's patches. no crashing here :+1:

**Comment by glocq** [comment] 2023-01-14 17:01
Hi! Sorry I didn't get to test the new version any sooner, but the issue appears to have been fixed for me as well :) Thank you!

**Closed** 2023-01-14 17:02 UTC
