### ISSUE TITLE
DSP GUI indicator and audio computation on startup (standalone)

### ISSUE THREAD

**Issue by angelfaraldo** [plugdata-team/plugdata#1305] opened 2023-11-24 22:28 UTC
The DSP GUI indicator is lit (ON) when initiating the standalone application, although the audio computation results to be effectively off when opening plugdata (as in vanilla). There seems to be a need of clicking the GUI button twice (off, and on again), for DSP to compute correctly.

Furthermore, when opening a patch containing a [loadbang] object, the audio engine turns ON on startup, but after 1 second approximately, it turns off (not the GUI indicator button, but the audio and VU's).  

(0.8.2 on an Intel Mac 2019 with Ventura 13.6.1)

**Comment by angelfaraldo** [comment] 2023-11-25 09:29
After further exploration, in my system, the following occurs:

(a) Opening a patch from the "Recently opened" list in plugdata, opens the patch CORRECTLY.
(b) Opening a patch from the "Open Patch" opption in plugdata, opens the patch, audio works for 1 sec. then stops.
(c) Dragging a patch to plugdata or selecting a patch in the OS to "open with..." plugdata, replicates behaviour (b)

- Turning audio computation OFF and then ON, brings the program back to normal behaviour.
- Replicating actions (b) and (c) when a patch is running and computing, turns audio computation OFF.
- In all scenarios, the GUI Indicator remains LIT (ON)

I hope this helps to understand the nature of the issue.

<img width="276" alt="test-patch-audio-on-load" src="https://github.com/plugdata-team/plugdata/assets/6861193/6a64b607-9445-4441-8f24-d3aa704f75ea">

**Comment by timothyschoen** [comment] 2023-12-07 00:35
Is this still an issue on the latest nightly builds? I can't reproduce this with Ventura on arm

**Comment by angelfaraldo** [comment] 2023-12-07 09:01
Yes, it is on 07-12-23 01:54 UTC. I've just checked previous releases and the problem goes back to 0.8.0-test from Sept 5.

As a matter of fact, after further testing, it is in a sort of unworkable condition: 

- Simply saving the patch (cmd+s) stops the audio computation roughly 1 sec after.
- Even creating other tilde objects stops audio computation (although not always).

I am teaching a class on Pd and my go-to distro was plugdata. We have been replicating this behaviour on multiple SOs (win 10/11 and mac intel/arm... and I recall that everybody in the classroom was having similar issues). I can try to report more precisely on that during the weekend. We have nonetheless gone back to 0.7.1, where this problem is not present. I will try later today in a MAC M2 w/ Sonoma.

SCREEN RECORDING:
https://github.com/plugdata-team/plugdata/assets/6861193/b89c6aca-bd54-465a-8486-e9de6d16be01

**Comment by dromer** [comment] 2023-12-07 09:06
I was able to replicate this on Linux by not even saving.

Super simple patch: `[noise~]-[dac~]` and then try to create `[~]` (non-existing tilde object) -> audio processing stops

**Comment by timothyschoen** [comment] 2023-12-07 14:10
> I was able to replicate this on Linux by not even saving.
> 
> Super simple patch: `[noise~]-[dac~]` and then try to create `[~]` (non-existing tilde object) -> audio processing stops
> 
> However to be fair: Pd is showing exactly the same behavior. Maybe it's some sort of internal protection? Interesting that this doesn't happen for you on `0.7.1`

So maybe this bug was introduced in pd-0.54?

**Comment by timothyschoen** [comment] 2023-12-07 14:18
I can't reproduce this with saving for some reason, but I could with creating an invalid object. I just pushed a fix for that on develop.

@angelfaraldo I'm not sure if this will also help with the other DSP issues, but it might help? I'll make sure we have this sorted out before the next release, so you can get back to teaching! Could you try this nightly build once it's done? https://github.com/plugdata-team/plugdata/actions/runs/7129433121

**Comment by angelfaraldo** [comment] 2023-12-07 14:27
I have just tried replicating the same behaviour on a Mac Studio M2 with Sonoma: and none of the above-mentioned problems are happening. Plugdata 0.8.2 works as expected. 

When it comes to my intel mac, in my machine, Pd-vanilla 0-54-1 works also as expected for me: it starts up with audio off, and from there it operates normally.

@timothyschoen: thanks for all your efforts, I will try the nightly build when done, and report back.

**Comment by dromer** [comment] 2023-12-07 14:31
@timothyschoen I can confirm that with that latest fix the reproducible case I described is at least solved.

**Comment by timothyschoen** [comment] 2023-12-07 14:46
> I have just tried replicating the same behaviour on a Mac Studio M2 with Sonoma: and none of the above-mentioned problems are happening. Plugdata 0.8.2 works as expected.

That's interesting, so it's no coincidence it works on my M1 MBP. I'll try it on my old macbook, see if it happens there

**Comment by angelfaraldo** [comment] 2023-12-07 23:43
Hi! I've just tested the last nightly build (7604e0c) on an intel MBP and it seems to finally work. Tomorrow I will make more detailed testing, but so far, audio computation does not stop!! (this is so good!)

**Closed** 2023-12-18 04:12 UTC
