### ISSUE TITLE
else [out] are always on full volume

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#516] opened 2023-02-10 05:57 UTC
the volume slider does nothing

(this has audio)

https://user-images.githubusercontent.com/86204514/218009613-7332cd0d-6157-4775-bef3-111f2b21a58a.mp4

bonus fun: try connecting the oscillator output to the second inlet of [out4~] or [out8~] the frequency changes somehow!

**Comment by timothyschoen** [comment] 2023-02-11 02:09
This was a bug in pd caused by the new multichannel signals, I've downgraded to a more stable version of Pd temporarily. Update your submodules and it should be fixed!

**Closed by timothyschoen** 2023-02-11 02:09 UTC
