### ISSUE TITLE
[bug] patch that is closed still running in the background

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1541] opened 2024-04-28 02:51 UTC
Very strange and no idea if it can be reproduced, but I have a state that I briefly had opened a patch that prints numbers to the console, I closed the patch but I still see the numbers being printed!

**Comment by FlachyJoe** [comment] 2024-04-28 10:14
If the transmission of characters is very fast there may be a delay in the display while the buffer empties.

**Comment by dromer** [comment] 2024-04-28 10:17
It was not, like every 500ms or so.

And now trying to open the patch again it says: `Patch is already open` which proves that it's still running in the background somehow o.O

**Comment by dromer** [comment] 2024-04-28 10:24
I just built the latest develop and it no longer does this, so maybe it was a weird fluke? (I had restarted plugdata several times since finding this, though)

**Comment by timothyschoen** [comment] 2024-04-28 10:49
> I just built the latest develop and it no longer does this, so maybe it was a weird fluke? (I had restarted plugdata several times since finding this, though)

I'll keep this issue open and keep an eye out for it. It might be a bug that only happens every now and then?

**Comment by dromer** [comment] 2024-04-28 10:57
Yeah if it happens again I'll come back :)

**Comment by dromer** [comment] 2024-06-18 05:41
I had this again yesterday:

Open a patch that creates sound. Close the patch. No patches are open but I still hear the sound.

**Comment by dromer** [comment] 2024-06-21 15:42
I get this on any patch now, it's like the patch is running twice.

On loading the patch I see `Patch is already open` error in the console. Then when I close the patch I can't reopen it or I see a flood of `warning: ...: multiply defined`

**Comment by alcomposer** [comment] 2024-06-22 08:29
I can trigger this bug consistently with @tomara-x amaranth patch.

The issue is only triggered if I don't open the subpatch `pd-seq0` so maybe PD doesn't think we are closing the whole patch?

**Comment by dromer** [comment] 2024-06-22 09:11
A very basic test-patch that does it for me:

![2024-06-22_11-09](https://github.com/plugdata-team/plugdata/assets/1185977/da2795a5-77ab-47be-8b82-5ba32f9f8d05)

**Comment by timothyschoen** [comment] 2024-06-22 10:18
@alcomposer I see this is caused by the lastSplitPatches still holding references to the pd::Patch::Ptr. I wonder why we need to have a lastSplitPatches array though? Wouldn't it suffice to set the split index on the existing patches?

**Comment by timothyschoen** [comment] 2024-06-22 10:23
I guess we should just use a regular pointer here instead of Patch::Ptr

**Comment by timothyschoen** [comment] 2024-06-22 10:28
Fixed!

**Closed by timothyschoen** 2024-06-22 10:28 UTC

**Comment by dromer** [comment] 2024-06-22 11:04
yay! seems to properly close the patch now \o/
