### ISSUE TITLE
In max theme slider label doesn't show on background

### ISSUE THREAD

**Issue by kamomehettapi** [plugdata-team/plugdata#1992] opened 2024-12-02 03:33 UTC
It appears to default to a white-on-white text for max theme

Also notable - if you switch a theme the old slider colors remain, the bottom bar here was from default light theme

![](https://github.com/user-attachments/assets/d047cbcf-3dac-4102-b432-b7c7f7131db6)

**Comment by dromer** [comment] 2024-12-02 06:11
Because the label color is white and so is your background.
If you were to switch to a dark theme then the label would appear.

Not sure what the bug is here?

**Comment by dromer** [comment] 2024-12-04 08:36
@kamomehettapi thank you for explaining. Now I understand the nuance of what the problem is.

**Comment by timothyschoen** [comment] 2024-12-04 14:41
> Like if I change theme I want to change all hsliders to match

There is the "reset properties" button at the top of the inspector, but that will reset all your properties. Perhaps a reset button for colour would be good too? We can't just automatically switch it, because there is no way to tell for sure if the user set a custom colour or not.

The Max theme issue should be fixed with 0bac6aa6f

**Closed by timothyschoen** 2024-12-04 14:41 UTC
