### ISSUE TITLE
Visual glitches on Linux

### ISSUE THREAD

**Issue by hamoid** [plugdata-team/plugdata#1803] opened 2024-08-17 15:08 UTC
Hi! I'm following a tutorial while using Plugdata for the first time (0.9.1).

I'm seeing this kind of glitches:

https://github.com/user-attachments/assets/d40c387e-6341-4e35-a32d-79a4d02b24de

I'm on Arch Linux using i3wm, integrated Intel Haswell Gen7 GPU on a 10 year old laptop.
I think OPENGL works fine (I can develop programs using GLSL shaders, including compute shaders).

Do you have ideas on why this can happen?

Thank you :-)

**Comment by timothyschoen** [comment] 2024-08-18 14:12
Hi, thanks for reporting!

I've seen these kinds of glitches before, but I'm not sure how to consistently reproduced it. I've only ran into it myself once. Do you know a way to make this happen consistently? Or do I just need to try a lot?

**Comment by dromer** [comment] 2024-08-18 17:43
I have never seen these kind of glitches before. Does it happen on every zoom level?

**Comment by hamoid** [comment] 2024-08-18 19:56
Oh it was happening at every zoom level and I could reproduce it even after restarting Plugdata, but now that I've restarted the computer things are working fine! :-)

I wonder if I had updated some system packages and not restarted the computer...

I will update this issue if it ever happens again. Meanwhile I guess it can be closed.

Thank you :-)

**Comment by timothyschoen** [comment] 2024-08-18 20:05
I think I've found out: it happens after opening and closing the settings panel. I know why too, so fix is coming soon!
Keyboard glitch is a separate issue, I tried to optimise it, and must have broken it!

@dromer These bugs are probably because of pretty recent changes, so makes sense you haven't ran into them yet!

**Comment by dromer** [comment] 2024-08-19 15:47
> so makes sense

Well I update almost every day :P

**Comment by dromer** [comment] 2024-08-20 09:06
Ok builds work again, but all nanovg rendering seems to be very laggy.

**Comment by dromer** [comment] 2024-08-20 21:31
@timothyschoen yes-yes, much better!

**Comment by timothyschoen** [comment] 2024-08-26 00:43
Should be all fixed now!

**Closed by timothyschoen** 2024-08-26 00:43 UTC
