### ISSUE TITLE
Toolchain not found after downloading on fresh debian 12, plugdata 0.9.1

### ISSUE THREAD

**Issue by sensorium** [plugdata-team/plugdata#1810] opened 2024-08-21 08:51 UTC
Hi,
the Toolchain appears to download, but exporting dpf source or binary fails.  Try again, Toolchain is not found.  This cycle repeats.  This is a fresh install of plugdata 0.9.1 from repository on a fresh install of debian 12.  Am I missing something?

Thanks

**Comment by dromer** [comment] 2024-08-22 17:01
This seems a duplicate of https://github.com/plugdata-team/plugdata/issues/1807 ?

Please don't post the same issue multiple times.

**Comment by sensorium** [comment] 2024-08-23 01:03
Thanks, yes it might be the same issue, but the behaviour was different on each platform.  
On Ubuntustudio (issue #1807) the export window didn't reappear on subsequent attempts after the first botched Toolchain install.
On Debian, the Toolchain download window would appear each time.  On the successful attempt, I think I may have moved the plugdata window before trying to export (and the Toolchain download window appearing). On this occasion the permissions window was not hidden.
Not sure if these qualify as issues or just quirks, so I'll leave it to you whether to close them.
Thanks a lot for your help and all your work!

**Closed** 2024-08-23 13:52 UTC
